name: Synch To Forked Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository (A)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: main

      - name: Push to forked repository (B)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTO_ACTIONS }}
          repository: Inoansta/Spark-Front
          branch: main
          force: true
